"""Remove sentences

Revision ID: 7e055ec80be8
Revises: ba1495e604ba
Create Date: 2026-05-01 17:44:59.222680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e055ec80be8'
down_revision: Union[str, Sequence[str], None] = 'ba1495e604ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraphs', sa.Column('paragraph_text', sa.Text(), nullable=False))
    op.drop_column('paragraphs', 'sentences')
    op.drop_column('paragraphs', 'full_paragraph')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraphs', sa.Column('full_paragraph', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('paragraphs', sa.Column('sentences', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('paragraphs', 'paragraph_text')
    # ### end Alembic commands ###
