"""add paragraphs table

Revision ID: ba1495e604ba
Revises: 
Create Date: 2026-05-01 15:38:51.344769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy # type: ignore


# revision identifiers, used by Alembic.
revision: str = 'ba1495e604ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(), nullable=False),
    sa.Column('book', sa.String(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('pov', sa.String(), nullable=False),
    sa.Column('paragraph', sa.Integer(), nullable=False),
    sa.Column('full_paragraph', sa.Text(), nullable=False),
    sa.Column('sentences', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False), # type: ignore
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paragraphs_embedding', 'paragraphs', ['embedding'], unique=False, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paragraphs_embedding', table_name='paragraphs', postgresql_using='ivfflat')
    op.drop_table('paragraphs')
    # ### end Alembic commands ###
